name: Rails Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      
    - name: Run tests
      run: bundle exec rails test
